/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railwayatttendencemanagementsystem;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static railwayatttendencemanagementsystem.ChartDisplay.con;
import static railwayatttendencemanagementsystem.ChartDisplay.result;
import static railwayatttendencemanagementsystem.ChartDisplay.resultmeta;
import static railwayatttendencemanagementsystem.ChartDisplay.st;


/**
 *
 * @author ROHANRAJ
 */
public class NewChartDisplay extends javax.swing.JFrame {

   java.sql.Connection con = null;
   java.sql.Statement st = null;
   java.sql.ResultSet result = null;
   //java.sql.ResultSetMetaData resultmeta;
    DefaultTableModel m1;
    public NewChartDisplay(String var) throws SQLException {
        try {
          initComponents();
          Class.forName("com.mysql.jdbc.Driver");
          m1 = (DefaultTableModel) chart.getModel();
          con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/pamsystem","root","root");
          st = con.createStatement();
           result = st.executeQuery("SELECT * FROM cp12155 where coachno = '"+var+"'");
//           resultmeta = result.getMetaData();
//           int noofcoloum = resultmeta.getColumnCount();
  //         System.out.print(""+noofcoloum);
          
    while(result.next())
    {
    String s1,s2,s3,s4,s5,s6,s7,s8;
    s1 = result.getString(1);
    s2 = result.getString(2);
    s3 = result.getString(3);
    s4 = result.getString(4);
    s5 = result.getString(5);
    s6 = result.getString(6);
    s7 = result.getString(7);
    s8 = result.getString(8);
    
    m1.addRow(new Object[]{s1,s2,s3,s4,s5,s6,s7,s8});
    }
      } catch (ClassNotFoundException ex) {
         JOptionPane.showMessageDialog(null,"error in conection "+ ex);
      }
    }

    private NewChartDisplay() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chart = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("HOME");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        chart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PNR NO", "NAME", "GENDER", "AGE", "COACH NO", "SEAT NO", "BIRTH LOCATION", "STATUS"
            }
        ));
        jScrollPane2.setViewportView(chart);

        jLabel4.setText("CHART DISPLAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(287, 287, 287)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewChartDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewChartDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewChartDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewChartDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new NewChartDisplay().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable chart;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
